-- PROGRESSION - 1
CREATE TABLE city
(ID NUMBER(11) NOT NULL,
NAME VARCHAR(50) NOT NULL,
CONSTRAINT city_pk PRIMARY KEY (ID)
);

-- 1. **Create table city**


-- 2. **Create table referee**
CREATE TABLE referee
(ID NUMBER(11) NOT NULL,
NAME VARCHAR(50) NOT NULL,
CONSTRAINT referee_pk PRIMARY KEY (ID)
);
-- 3. **Create table innings**
CREATE TABLE innings
(ID NUMBER(11) NOT NULL,
INNINGS_NUMBER NUMBER(11) NOT NULL,
CONSTRAINT innings_pk PRIMARY KEY (ID)
);
-- 4. **Create table extra_type**
CREATE TABLE extra_type
(ID NUMBER(11) NOT NULL,
NAME VARCHAR(50) NOT NULL,
CONSTRAINT extra_type PRIMARY KEY (ID)
);
-- 5. **Create table skill**
CREATE TABLE skill
(ID NUMBER(11) NOT NULL,
NAME VARCHAR(50) NOT NULL,
CONSTRAINT skill PRIMARY KEY (ID)
);
-- 6. **Create table team**
CREATE TABLE team
(ID NUMBER(11) NOT NULL,
NAME VARCHAR(50) NOT NULL,
COACH VARCHAR(50) NOT NULL,
CAPTAIN NUMBER(11) NOT NULL,
HOME_CITY NUMBER(11) NOT NULL,
CONSTRAINT FK_TEAM FOREIGN KEY(HOME_CITY) 
REFERENCES CITY(ID),
CONSTRAINT team PRIMARY KEY (ID)
);
-- 7. **Create table player**
CREATE TABLE PLAYER
(ID NUMBER(11) NOT NULL,
NAME VARCHAR(50) NOT NULL,
COUNTRY VARCHAR(50) NOT NULL,
SKILL_ID NUMBER(11) NOT NULL,
TEAM_ID NUMBER(11) NOT NULL,
CONSTRAINT FK_PLAYER1 FOREIGN KEY(SKILL_ID) 
REFERENCES SKILL(ID),
CONSTRAINT FK_PLAYER2 FOREIGN KEY(TEAM_ID) 
REFERENCES TEAM(ID),
CONSTRAINT PLAYER PRIMARY KEY (ID)
);
-- 8. **Create table venue**
CREATE TABLE VENUE
(ID NUMBER(11) NOT NULL,
STADIUM_NAME VARCHAR(50) NOT NULL,
CITY_ID NUMBER(11) NOT NULL,
CONSTRAINT FK_VENUE FOREIGN KEY(CITY_ID) 
REFERENCES CITY(ID),
CONSTRAINT VENUE PRIMARY KEY (ID)
);
-- 9. **Create table event**
CREATE TABLE EVENT
(ID NUMBER(11) NOT NULL,
EVENT_NO NUMBER(11) NOT NULL,
RAID_POINTS NUMBER(11) NOT NULL,
DEFENDING_POINTS NUMBER(11) NOT NULL,
CLOCK_IN_SECONDS NUMBER(11) NOT NULL,
TEAM_ONE_SCORE NUMBER(11) NOT NULL,
TEAM_TWO_SCORE NUMBER(11) NOT NULL,
INNINGS_ID NUMBER(11) NOT NULL,
CONSTRAINT FK_EVENT FOREIGN KEY(INNINGS_ID) 
REFERENCES INNINGS(ID),
RAIDER_ID NUMBER(11) NOT NULL,
CONSTRAINT FK_EVENT1 FOREIGN KEY(RAIDER_ID) 
REFERENCES PLAYER(ID),
CONSTRAINT EVENT PRIMARY KEY (ID)
);
-- 10. **Create table extra_event**
CREATE TABLE EXTRA_EVENT
(ID NUMBER(11) NOT NULL,
POINTS NUMBER(11) NOT NULL,
EVENT_ID NUMBER(11) NOT NULL,
CONSTRAINT FK_EXTRA1 FOREIGN KEY(EVENT_ID) 
REFERENCES EVENT(ID),
EXTRA_TYPE_ID NUMBER(11) NOT NULL,
CONSTRAINT FK_EXTRA2 FOREIGN KEY(EXTRA_TYPE_ID) 
REFERENCES EXTRA_TYPE(ID),
SCORING_TEAM_ID NUMBER(11) NOT NULL,
CONSTRAINT FK_TEAM1 FOREIGN KEY(SCORING_TEAM_ID) 
REFERENCES TEAM(ID),
CONSTRAINT EXTRA_EVENT PRIMARY KEY (ID)
);
-- 11. **Create table outcome**
CREATE TABLE OUTCOME
(ID NUMBER(11) NOT NULL,
STATUS VARCHAR(50) NOT NULL,
WINNER_TEAM_ID NUMBER(11) NULL,
CONSTRAINT FK_WINNERTEAM1 FOREIGN KEY(WINNER_TEAM_ID) 
REFERENCES TEAM(ID),
SCORE NUMBER(11) NULL,
PLAYER_OF_MATCH NUMBER(11)NOT NULL,
CONSTRAINT FK_MATCH1 FOREIGN KEY(PLAYER_OF_MATCH) 
REFERENCES PLAYER(ID),
CONSTRAINT OUTCOME PRIMARY KEY (ID)
);
-- 12. **Create table game**
CREATE TABLE GAME
(ID NUMBER(11) NOT NULL,
GAME_DATE DATE NOT NULL,
TEAM_ID_1 NUMBER(11)NOT NULL,
CONSTRAINT FK_TEAMID1 FOREIGN KEY(TEAM_ID_1) 
REFERENCES TEAM(ID),
TEAM_ID_2 NUMBER(11)NOT NULL,
CONSTRAINT FK_TEAM2 FOREIGN KEY(TEAM_ID_2) 
REFERENCES TEAM(ID),
VENUE_ID NUMBER(11)NOT NULL,
CONSTRAINT FK_VENUEID FOREIGN KEY(VENUE_ID) 
REFERENCES VENUE(ID),
REFEREE_ID_1 NUMBER(11)NOT NULL,
CONSTRAINT FK_REFEREEID1 FOREIGN KEY(REFEREE_ID_1) 
REFERENCES REFEREE(ID),
REFEREE_ID_2 NUMBER(11)NOT NULL,
CONSTRAINT FK_REFEREE2 FOREIGN KEY(REFEREE_ID_2) 
REFERENCES REFEREE(ID),
FIRST_INNINGS_ID NUMBER(11)NOT NULL,
CONSTRAINT FK_FIRSTINNINGS1 FOREIGN KEY(FIRST_INNINGS_ID) 
REFERENCES INNINGS(ID),
SECOND_INNINGS_ID NUMBER(11)NOT NULL,
CONSTRAINT FK_SECONDINNINGS2 FOREIGN KEY(SECOND_INNINGS_ID) 
REFERENCES INNINGS(ID),
CONSTRAINT GAME PRIMARY KEY (ID)
);
-- 13. **Drop table city**
ALTER TABLE TEAM DROP CONSTRAINT FK_TEAM;
ALTER TABLE VENUE DROP CONSTRAINT FK_VENUE;
DROP TABLE CITY;
-- 14. **Drop table innings**
ALTER TABLE EVENT DROP CONSTRAINT FK_EVENT;
ALTER TABLE GAME DROP CONSTRAINT FK_FIRSTINNINGS1;
ALTER TABLE GAME DROP CONSTRAINT FK_SECONDINNINGS2;
DROP TABLE INNINGS;
-- 15. **Drop table skill**
ALTER TABLE PLAYER DROP CONSTRAINT FK_PLAYER1;
DROP TABLE SKILL;
-- 16. **Drop table extra_type**
ALTER TABLE EXTRA_EVENT DROP CONSTRAINT FK_EXTRA2;
DROP TABLE EXTRA_TYPE;